version: '3.8'
services:
  db:
    image: postgres:15
    container_name: messier-db
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: messier
    ports:
      - "5432:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
